# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
